# Generated by Django 5.1.1 on 2024-09-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='carname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='reviewer_name',
        ),
    ]
