# Generated by Django 5.1.1 on 2024-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreviews', '0004_item_delete_carreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('review_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
